/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWiadomosciRouteImport } from './routes/admin.wiadomosci'
import { Route as AdminUstawieniaRouteImport } from './routes/admin.ustawienia'
import { Route as AdminTrafficRouteImport } from './routes/admin.traffic'
import { Route as AdminTipyRouteImport } from './routes/admin.tipy'
import { Route as AdminSubskrybenciRouteImport } from './routes/admin.subskrybenci'
import { Route as AdminStatystykiRouteImport } from './routes/admin.statystyki'
import { Route as AdminPlatnosciRouteImport } from './routes/admin.platnosci'
import { Route as AdminNowyTypRouteImport } from './routes/admin.nowy-typ'

const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWiadomosciRoute = AdminWiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUstawieniaRoute = AdminUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrafficRoute = AdminTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTipyRoute = AdminTipyRouteImport.update({
  id: '/tipy',
  path: '/tipy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubskrybenciRoute = AdminSubskrybenciRouteImport.update({
  id: '/subskrybenci',
  path: '/subskrybenci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatystykiRoute = AdminStatystykiRouteImport.update({
  id: '/statystyki',
  path: '/statystyki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlatnosciRoute = AdminPlatnosciRouteImport.update({
  id: '/platnosci',
  path: '/platnosci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNowyTypRoute = AdminNowyTypRouteImport.update({
  id: '/nowy-typ',
  path: '/nowy-typ',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/admin/nowy-typ': typeof AdminNowyTypRoute
  '/admin/platnosci': typeof AdminPlatnosciRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/subskrybenci': typeof AdminSubskrybenciRoute
  '/admin/tipy': typeof AdminTipyRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/admin/nowy-typ': typeof AdminNowyTypRoute
  '/admin/platnosci': typeof AdminPlatnosciRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/subskrybenci': typeof AdminSubskrybenciRoute
  '/admin/tipy': typeof AdminTipyRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/admin/nowy-typ': typeof AdminNowyTypRoute
  '/admin/platnosci': typeof AdminPlatnosciRoute
  '/admin/statystyki': typeof AdminStatystykiRoute
  '/admin/subskrybenci': typeof AdminSubskrybenciRoute
  '/admin/tipy': typeof AdminTipyRoute
  '/admin/traffic': typeof AdminTrafficRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wiadomosci': typeof AdminWiadomosciRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/admin/nowy-typ'
    | '/admin/platnosci'
    | '/admin/statystyki'
    | '/admin/subskrybenci'
    | '/admin/tipy'
    | '/admin/traffic'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/admin/nowy-typ'
    | '/admin/platnosci'
    | '/admin/statystyki'
    | '/admin/subskrybenci'
    | '/admin/tipy'
    | '/admin/traffic'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/admin/nowy-typ'
    | '/admin/platnosci'
    | '/admin/statystyki'
    | '/admin/subskrybenci'
    | '/admin/tipy'
    | '/admin/traffic'
    | '/admin/ustawienia'
    | '/admin/wiadomosci'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RegulaminRoute: typeof RegulaminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wiadomosci': {
      id: '/admin/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/admin/wiadomosci'
      preLoaderRoute: typeof AdminWiadomosciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ustawienia': {
      id: '/admin/ustawienia'
      path: '/ustawienia'
      fullPath: '/admin/ustawienia'
      preLoaderRoute: typeof AdminUstawieniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traffic': {
      id: '/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AdminTrafficRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tipy': {
      id: '/admin/tipy'
      path: '/tipy'
      fullPath: '/admin/tipy'
      preLoaderRoute: typeof AdminTipyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subskrybenci': {
      id: '/admin/subskrybenci'
      path: '/subskrybenci'
      fullPath: '/admin/subskrybenci'
      preLoaderRoute: typeof AdminSubskrybenciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statystyki': {
      id: '/admin/statystyki'
      path: '/statystyki'
      fullPath: '/admin/statystyki'
      preLoaderRoute: typeof AdminStatystykiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/platnosci': {
      id: '/admin/platnosci'
      path: '/platnosci'
      fullPath: '/admin/platnosci'
      preLoaderRoute: typeof AdminPlatnosciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nowy-typ': {
      id: '/admin/nowy-typ'
      path: '/nowy-typ'
      fullPath: '/admin/nowy-typ'
      preLoaderRoute: typeof AdminNowyTypRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNowyTypRoute: typeof AdminNowyTypRoute
  AdminPlatnosciRoute: typeof AdminPlatnosciRoute
  AdminStatystykiRoute: typeof AdminStatystykiRoute
  AdminSubskrybenciRoute: typeof AdminSubskrybenciRoute
  AdminTipyRoute: typeof AdminTipyRoute
  AdminTrafficRoute: typeof AdminTrafficRoute
  AdminUstawieniaRoute: typeof AdminUstawieniaRoute
  AdminWiadomosciRoute: typeof AdminWiadomosciRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNowyTypRoute: AdminNowyTypRoute,
  AdminPlatnosciRoute: AdminPlatnosciRoute,
  AdminStatystykiRoute: AdminStatystykiRoute,
  AdminSubskrybenciRoute: AdminSubskrybenciRoute,
  AdminTipyRoute: AdminTipyRoute,
  AdminTrafficRoute: AdminTrafficRoute,
  AdminUstawieniaRoute: AdminUstawieniaRoute,
  AdminWiadomosciRoute: AdminWiadomosciRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RegulaminRoute: RegulaminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
